### PR TITLE
Wrong use of generics in ArrayComparator#Reverse #24

### PR DESCRIPTION
**Pull request by ivanjunckes**

### CODE REVIEW

**Comment by dmarkov** [comment]
@ivanjunckes Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@pinaf it's yours, please review

**Comment by pinaf** [comment]
@ivanjunckes I don't think this is correct... `<T extends Comparable<T>` seems recursive to me. Is this fixing any open issues?

**Comment by pinaf** [comment]
@ivanjunckes ok I see this is for #21, please add a link to the issue in your first comment.

**Comment by pinaf** [comment]
@ivanjunckes perhaps you mean `<T extends Comparable>`?

**Comment by pinaf** [comment]
@ivanjunckes also, let's add a unit test.

**Comment by pinaf** [comment]
@ivanjunckes ping

**Comment by pinaf** [comment]
@ivanjunckes please close the PR

**Comment by pinaf** [comment]
@ivanjunckes this issue has already been fixed in another PR. please close it.

**Comment by dmarkov** [comment]
@pinaf thanks, I just added **22 mins** to your account, payment `AP-7JH883660N440973W`, 526 hours spent

review comments (c=7) added as a bonus

+22 added to your rating, current score is: [+6444](http://www.netbout.com/b/35128?open=rating)

**Pull request closed without merging**
