### PR TITLE
Deprecated for mutators

### PR DESCRIPTION
**Pull request by nesterov-n**
This reffers #17

### CODE REVIEW

**Comment by dmarkov** [comment]
@nesterov-n Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@mkordas could you please review this pull request

**Comment by mkordas** [comment]
@nesterov-n I'm on it

**Comment by mkordas** [comment]
@nesterov-n can you please check failing build?

**Comment by mkordas** [comment]
@nesterov-n now I see. Please just suppress `NoJavadocForOverrideMethods` for these classes and add proper `@deprecated`.

**Comment by nesterov-n** [comment]
@mkordas  can you help me? How can I suppress `NoJavadocForOverrideMethods` check for class? I'm not familiar with qulice tool

**Comment by mkordas** [comment]
@nesterov-n here you have sample suppression: https://github.com/teamed/qulice/blob/4243a5b5e2a05f01e8af9dcb353f4a798ca36aaf/qulice-maven-plugin/src/it/hibernate-validator-check/src/main/java/com/qulice/foo/Sample.java#L18

**Comment by mkordas** [comment]
@nesterov-n ping

**Comment by nesterov-n** [comment]
@mkordas Adding deprecated javaDoc tag causes too many check fails (JavadocMethodCheck, RegexpMultilineCheck). Maybe best way is suppress MissingDeprecatedCheck for whole file?

**Comment by mkordas** [comment]
@nesterov-n OK, I'm fine with this solution. It should be clear why these methods are deprecated without additional docs.

**Comment by mkordas** [comment]
@nesterov-n looks good!

**Comment by mkordas** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@mkordas paid, thanks, added **23 mins** to your account, payment `56de85744b766c3bd800041a`, 90 hours and 11 mins was spent. review comments (c=8) added as a bonus. added +23 to your rating, now it is equal to [+8319](http://www.netbout.com/b/36080?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
