### PR TITLE
#6 - update copyright to 2015

### PR DESCRIPTION
**Pull request by nathansgreen**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, I'll ask someone to do a code review here, thanks for your pull request

**Comment by dmarkov** [comment]
@krzyk it's yours, please review

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@krzyk Thanks so much! Your account was topped up for **16 mins** (transaction ID is `50300948`); +16 to your rating, your total score is [+1696](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
