### PR TITLE
#10 Estimate project size

### PR DESCRIPTION
**Pull request by super132**
For task #10, produce the estimate file for project.

### CODE REVIEW

**Comment by super132** [comment]
@dmarkov please review this PR. Thanks.

**Comment by dmarkov** [comment]
@super132 I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@caarlos0 this pull request is for you, please review

**Comment by dmarkov** [comment]
> @dmarkov please review this PR. Thanks.

@super132 will take a look, thanks

**Comment by caarlos0** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@rultor deploy

**Comment by caarlos0** [comment]
@yegor256 didn't get paid here

**Comment by caarlos0** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@dmarkov pls add extra 15 mins to @caarlos0

**Comment by caarlos0** [comment]
@yegor256 didn't get paid for this one too

**Pull request merged**
